### ISSUE TITLE
Support `0x` prefix

### ISSUE THREAD

**Issue by TmLev** [inspier/hexlit#3]
Is it possible to support `0x` prefix? Like so:

```rust
let address: [u8; 20] = hexlit::hex!("0xe9e7cea3dedca5984780bafc599bd69add087d56");
```

**Comment by inspier** [comment]
That turns out to be kind of difficult to support with how the code works today, I'll see if I can come up with something, but might be a bit until I can take a look at this. I would also be willing to accept a PR for this if you come up with anything.

**Comment by inspier** [comment]
@TmLev Added support in [0.5.5](https://crates.io/crates/hexlit). Lmk if you run into any issues with this.

**Comment by TmLev** [comment]
@inspier, works like a charm, thank you!
